blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs.urls')),
]

blogs/urls.py
"""Определяет схемы URL для blogs"""

from django.urls import path

from . import views

app_name = 'blogs'
urlpatterns = [
	# Домашняя страница
	path('', views.index, name='index'),
	# Страница для добавления новой записи
	path('new_text/', views.new_text, name='new_text'),
	# Страница для редактирования записи
	path('edit_text/<int:texts_id>', views.edit_text, name='edit_text'),
]

users/urls.py
"""Определяет схемы URL для пользователей"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
	# Включить URL авторизации по умолчанию
	path('', include('django.contrib.auth.urls')),
	# Страница регистрации
	path('register/', views.register, name='register'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Создайте здесь свои модели.

class BlogPost(models.Model):
	"""Создание простого блога для пользователей"""
	title = models.CharField(max_length=200)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		"""Возвращает строковое предсавление модели"""
		return self.title

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms

from .models import BlogPost

class BlogPostForm(forms.ModelForm):
	class Meta:
		model = BlogPost
		fields = ['title', 'text']
		labels = {'text': ''}
		

blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import BlogPost
from .forms import BlogPostForm


# Создайте здесь свои представления.

def index(request):
	"""Домашняя страница приложения Blog"""
	title = BlogPost.objects.all()
	text = BlogPost.objects.order_by('-date_added')
	context = {'title': title, 'text': text}
	return render(request, 'blogs/index.html', context)

@login_required
def new_text(request):
	"""Определяет новую запись"""
	if request.method != 'POST':
		# Данные не отправлялись; создается пустая форма
		form = BlogPostForm()
	else:
		# Отправлены данные POST; обработать данные
		form = BlogPostForm(data=request.POST)
		if form.is_valid():
			new_text= form.save(commit=False)
			new_text.owner = request.user
			new_text.save()
			return redirect('blogs:index')

	# Вывести пустую или недействительную форму
	context = {'form': form}
	return render(request, 'blogs/new_text.html', context)

@login_required
def edit_text(request, texts_id):
	"""Редактирует существующую запись"""
	texts = BlogPost.objects.get(id=texts_id)
	check_text_owner(texts, request)
	if request.method != 'POST':
		# Исходный запрос; форма заполняется данными текущей записи
		form = BlogPostForm(instance=texts)
	else:
		# Отправка данных POST; обработать данные
		form = BlogPostForm(instance=texts, data=request.POST)
		if form.is_valid():

			form.save()
			return redirect('blogs:index')

	context = { 'texts': texts, 'form': form}
	return render(request, 'blogs/edit_text.html', context)

def check_text_owner(texts, request):
	if texts.owner != request.user:
		raise Http404

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


# Создайте здесть свои представления

def register(request):
	"""Регистрирует нового пользователя"""
	if request.method != 'POST':
		# Выводит пустую форму регистрации
		form = UserCreationForm()
	else:
		# Обработка заполненной формы
		form = UserCreationForm(data=request.POST)

		if form.is_valid():
			new_user = form.save()
			# Выполнение входа и перенаправление на домашнюю страницу
			login(request, new_user)
			return redirect('blogs:index')

	# Вывести пустую или недействительную форму
	context = {'form': form}
	return render(request, 'registration/register.html', context)

blogs/templates/blogs/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html>
<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, 
    shrink-to-fit=no">
   <title>Блог</title>
   {% bootstrap_css %}
   {% bootstrap_javascript jquery='full' %}
</head>
<body>
   <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
      <a class="navbar-brand" href="{% url 'blogs:index' %}">
         Блог</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarCollapse" aria-controls="navbarCollapse">
         <span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
         <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
               <li class="nav-item">
                  <span class="navbar-text">Привет, {{ user.username }}!</span>
               </li>
               <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:logout' %}">Выход</a>
               </li>
            {% else %}
               <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
               </li>
               <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:login' %}">Логин</a>
               </li>
            {% endif %}
         </ul>
      </div>
   </nav>

   <main role="main" class="container">
      <div class="pb-2 mb-2 border-bottom">
         {% block page_header %}{% endblock page_header %}
      </div>
      <div>
         {% block content %}{% endblock content %}
      </div>
   </main>
</body>
</html>

blogs/templates/blogs/edit_text.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <p>Редактировать запись</p>
{% endblock page_header %}

{% block content %}
  <form method="post" action="{% url 'blogs:edit_text' texts.id %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">добавить запись</button>
    {% endbuttons %}
  </form>

{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block page_header %}
  <p>{{ texts }}</p>
{% endblock page_header %}

{% block content %}
  <p>
<a href="{% url 'blogs:new_text' %}">Добавить новую запись</a>
  </p>
  {% for texts in text %}
    <div class="card mb-3">
      <p class="card-header">
        {{ texts.date_added|date:'M d, Y H:i' }}
        <small><a href="{% url 'blogs:edit_text' texts.id %}">Редактировать запись</a>
        </small>
      </p>
      <div class="card-body">
        {{ texts.text|linebreaks }}
      </div>
    </div>
  {% endfor %}
  

{% endblock content %}

blogs/templates/blogs/new_text.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <p>Добавьте ноую запись</p>
{% endblock page_header %}

{% block content %}
  <form method="post" action="{% url 'blogs:new_text' %}" class="form">
     {% csrf_token %}
     {% bootstrap_form form %}
     {% buttons %}
      <button name="submit" class="btn btn-primary">добавить запись</button>
     {% endbuttons %}
     
     <input type="hidden" name="next"
       value="{% url 'blogs:index' %}" />
  </form>

{% endblock content %}